Creación documentación integraciones api fac 229
Construplaza/Documencion-Integracion-APIs pull request #1
Opened 2024-08-12 18:16 UTC by andreicacalderon22

Solicitud de Merge a Documentación de Proyecto de Apis

Descripción : Se adjunta el readme necesario para crear la documentación del proyecto de Api´s

Referencias:
Este PR soluciona el FAC 229 relacionado con Creación documentación integraciones.

2024-08-15 00:07 UTC, patrick-ocampo requested changes

2024-08-15 00:07 UTC, patrick-ocampo commented on Documentacion/README.md
> +- Ejecutar solicitudes GET y POST para obtener o enviar todos los datos necesarios.
Aqui diria metodos de HTTP para no limitar a solo GET y POST

2024-08-15 00:07 UTC, patrick-ocampo commented on Documentacion/README.md
> +   - [Fase 3 - Consultar Productos de Pedido Especial](#-fase-3---consultar-productos-de-pedido-especial)
me parece que hay mas fases porque escuche de Esteban, quizas validarlo nada mas

2024-08-15 00:07 UTC, patrick-ocampo commented on Documentacion/README.md
> +- Consultar y generar pedidos especiales (productos que no manejamos).
creo que esto de pedidos especiales es lo mismo que generar ordenes automatizadas

2024-08-15 00:07 UTC, patrick-ocampo commented on Documentacion/README.md
> +- Nombre de Artículo
nombre es descripcion o SKU?

2024-08-15 00:07 UTC, patrick-ocampo commented on Documentacion/README.md
> +- Nombre de Artículo
en el resto creo que agregaria el tipo de dato que es, decimal, string, etc

2024-08-15 00:07 UTC, patrick-ocampo commented on Documentacion/README.md
> +## Requisitos del Proyecto
aqui agregaria habilitar el espacio de dev y luego hablar de pruebas para terminar en prod

2024-08-15 00:53 UTC, andreicacalderon22 commented on Documentacion/README.md
> +   - [Fase 3 - Consultar Productos de Pedido Especial](#-fase-3---consultar-productos-de-pedido-especial)
Revise pero en el mensaje que me envió me habla de esas tres nada más, pero el viernes temprano le consulto si hay más de 3

2024-08-16 18:03 UTC, andreicacalderon22 commented on Documentacion/README.md
> +- Ejecutar solicitudes GET y POST para obtener o enviar todos los datos necesarios.
Listo agregue solo como metodos

2024-08-16 18:04 UTC, andreicacalderon22 commented on Documentacion/README.md
> +- Consultar y generar pedidos especiales (productos que no manejamos).
Si es lo mismo, se elimino esa linea

2024-08-16 18:04 UTC, andreicacalderon22 commented on Documentacion/README.md
> +- Nombre de Artículo
Si se creo una tabla para más orden, con el tipo, y ejemplo

2024-08-16 18:04 UTC, andreicacalderon22 commented on Documentacion/README.md
> +## Requisitos del Proyecto
Listo se agrego esto dentro de la funcionalidad

2024-08-16 18:15 UTC, merged